services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"      # Jenkins Web UI
      - "50000:50000"    # For Jenkins agents (future)
    volumes:
      - jenkins_home:/var/jenkins_home
      # Optional: allows Jenkins to use Docker commands inside container
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
