sonar.projectKey=BlockFund
sonar.projectName=BlockFund
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,smart-contract/contracts
sonar.tests=smart-contract/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/artifacts/**,**/cache/**,**/coverage/**,**/ignition/**,**/test_backup/**,**/contracts/Counter.sol

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info